//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET1 {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox RegId;
		
		protected System.Web.UI.WebControls.TextBox Name;
		
		protected System.Web.UI.WebControls.TextBox Marks;
		
		protected System.Web.UI.WebControls.TextBox Address;
		
		protected System.Web.UI.WebControls.Button btn;
		
		protected System.Web.UI.WebControls.GridView GvData;
		
		protected System.Web.UI.WebControls.Label lblId;
		
		protected System.Web.UI.WebControls.TextBox txtId;
		
		protected System.Web.UI.WebControls.LinkButton btnEdit;
		
		protected System.Web.UI.WebControls.LinkButton btnDelete;
		
		protected System.Web.UI.WebControls.LinkButton btnUpdate;
		
		protected System.Web.UI.WebControls.LinkButton btnCancel;
	}
}
