//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET1 {
	
	
	public partial class FormPage {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblName;
		
		protected System.Web.UI.WebControls.TextBox textName;
		
		protected System.Web.UI.WebControls.Label lblAddress;
		
		protected System.Web.UI.WebControls.TextBox textAddress;
		
		protected System.Web.UI.WebControls.Label lblAcademic;
		
		protected System.Web.UI.WebControls.ListBox academicListBox;
		
		protected System.Web.UI.WebControls.Label GenderLbl;
		
		protected System.Web.UI.WebControls.RadioButton radioMale;
		
		protected System.Web.UI.WebControls.RadioButton radioFemale;
		
		protected System.Web.UI.WebControls.CheckBox consentCheck;
		
		protected System.Web.UI.WebControls.Label ConsentLbl;
		
		protected System.Web.UI.WebControls.Button submitButton;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl resultDiv;
		
		protected System.Web.UI.WebControls.Label lblResult;
	}
}
