//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET1 {
	
	
	public partial class StudentFormApp {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvName;
		
		protected System.Web.UI.WebControls.TextBox txtAge;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvAge;
		
		protected System.Web.UI.WebControls.RangeValidator rvAge;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator revEmail;
		
		protected System.Web.UI.WebControls.TextBox txtPhone;
		
		protected System.Web.UI.WebControls.CustomValidator cvPhone;
		
		protected System.Web.UI.WebControls.Button btnAddStudent;
		
		protected System.Web.UI.WebControls.ValidationSummary vsSummary;
		
		protected System.Web.UI.WebControls.GridView gvStudents;
	}
}
